[package]
name = "io-reactor"
version = "0.1.0"
description = "Rust implementation of reactor pattern for I/O resources"
authors = ["Dr. Maxim Orlovsky <orlovsky@ubideco.org>"]
keywords = ["reactor", "I/O", "patterns", "concurrency", "poll"]
categories = ["concurrency", "asynchronous", "network-programming", "rust-patterns"]
homepage = "https://github.com/rust-amplify"
repository = "https://github.com/rust-amplify/io-reactor"
rust-version = "1.65"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[lib]
name = "reactor"

[dependencies]
amplify = "4.0.0-beta.1"
crossbeam-channel = "0.5.6"
popol = { version = "1.0.0", git = "https://github.com/Cyphernet-WG/popol", branch = "api", optional = true }
polling = { version = "2.4.0", optional = true }
epoll = { version = "4.3.1", optional = true }
mio = { version = "0.8.5", optional = true }
log = { version = "0.4.17", optional = true, features = ["kv_unstable"] }
libc = "0.2.139"

[features]
default = ["popol"]
all = ["popol", "polling", "epoll", "mio", "log"]
