[package]
name = "io-reactor"
version = "0.1.0"
description = "Concurrent I/O resource management using reactor pattern"
authors = [
    "Dr. Maxim Orlovsky <orlovsky@ubideco.org>",
    "Alexis Sellier <alexis@cloudhead.io>"
]
keywords = ["reactor", "I/O", "patterns", "concurrency", "poll"]
categories = ["concurrency", "asynchronous", "network-programming", "rust-patterns"]
homepage = "https://github.com/rust-amplify"
repository = "https://github.com/rust-amplify/io-reactor"
rust-version = "1.60"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[lib]
name = "reactor"

[dependencies]
amplify = "4.0.0-beta.1"
crossbeam-channel = "0.5.6"
popol = { version = "2.1.0", optional = true }
polling = { version = "2.4.0", optional = true }
# epoll = { version = "4.3.1", optional = true } - NB: epoll not supported on MacOS
mio = { version = "0.8.5", optional = true }
log = { version = "0.4.17", optional = true, features = ["kv_unstable"] }
libc = "0.2.139"

[features]
default = ["popol"]
all = [
    "popol",
    "polling",
#    "epoll",
    "mio",
    "log"
]
